#!/usr/bin/env node
// ============================================================================
// build_web.mjs: builds both front-ends from their Tailwind sources.
//
//   npm run build:web            (or: node tools/build_web.mjs)
//
//   web/docs.css   -> docs/assets/site.css      (docs site, GitHub Pages)
//   web/webui.css  -> inlined into web/webui.html, together with
//                     docs/osd-format.js, then minified, gzipped and written
//                     to src/web_assets.h as a PROGMEM byte array.
//
// Tailwind only emits the utilities it finds in the scanned files, so the CSS
// stays as small as the markup allows. No dependencies beyond Tailwind itself:
// it uses node_modules/@tailwindcss/cli, or set TAILWIND_BIN to a standalone
// tailwindcss executable.
// ============================================================================
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import zlib from "node:zlib";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const r = (...p) => path.join(ROOT, ...p);
const kb = (n) => (n / 1024).toFixed(1) + " KB";

// ---------------------------------------------------------------- tailwind --
function tailwind(input, output) {
  const args = ["-i", input, "-o", output, "--minify"];
  if (process.env.TAILWIND_BIN) {
    execFileSync(process.env.TAILWIND_BIN, args, { cwd: ROOT, stdio: ["ignore", "ignore", "inherit"] });
    return;
  }
  const pkgDir = r("node_modules", "@tailwindcss", "cli");
  if (!fs.existsSync(pkgDir)) {
    console.error("Tailwind CLI not found. Run `npm install` first (or set TAILWIND_BIN).");
    process.exit(1);
  }
  const pkg = JSON.parse(fs.readFileSync(path.join(pkgDir, "package.json"), "utf8"));
  const bin = typeof pkg.bin === "string" ? pkg.bin : Object.values(pkg.bin)[0];
  execFileSync(process.execPath, [path.join(pkgDir, bin), ...args], { cwd: ROOT, stdio: ["ignore", "ignore", "inherit"] });
}

// ---------------------------------------------------------- light minifier --
// Deliberately conservative: gzip does the heavy lifting, this just drops
// comments and indentation. Only whole-line // comments and // comments
// preceded by 2+ spaces are removed, so "http://" inside strings is safe.
function minifyJs(js) {
  return js
    .replace(/\/\*(?!@|OSDFMT)[\s\S]*?\*\//g, "")
    .split("\n")
    .map((l) => l.replace(/\s{2,}\/\/.*$/, "").trim())
    .filter((l) => l && !l.startsWith("//"))
    .join("\n");
}
function minifyHtml(html) {
  return html
    .replace(/<!--(?!@)[\s\S]*?-->/g, "")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .join("\n")
    .replace(/>\n</g, "><");
}

// -------------------------------------------------------------- docs site --
fs.mkdirSync(r("docs", "assets"), { recursive: true });
tailwind("web/docs.css", "docs/assets/site.css");
console.log("docs/assets/site.css   " + kb(fs.statSync(r("docs", "assets", "site.css")).size));

// ------------------------------------------------------------ device web UI --
const tmp = r("web", ".build");
fs.mkdirSync(tmp, { recursive: true });
tailwind("web/webui.css", "web/.build/webui.css");
const css = fs.readFileSync(path.join(tmp, "webui.css"), "utf8").trim();

const osd = fs.readFileSync(r("docs", "osd-format.js"), "utf8");
const osdBlock = osd.match(/\/\*OSDFMT-BEGIN\*\/[\s\S]*?\/\*OSDFMT-END\*\//);
if (!osdBlock) throw new Error("docs/osd-format.js: OSDFMT-BEGIN/END markers not found");

let page = fs.readFileSync(r("web", "webui.html"), "utf8").replace(/\r\n/g, "\n");
// Minify each inline script, then the markup around it.
page = page.replace(/<script>([\s\S]*?)<\/script>/g, (_, js) => "<script>" + minifyJs(js) + "</script>");
page = minifyHtml(page);
page = page.replace("<!--@CSS-->", () => "<style>" + css + "</style>");
page = page.replace("/*@OSDFMT*/", () => minifyJs(osdBlock[0]));
if (page.includes("/*@OSDFMT*/") || page.includes("<!--@CSS-->")) throw new Error("placeholder not replaced");
fs.writeFileSync(path.join(tmp, "index.html"), page); // for previewing in a browser

const raw = Buffer.from(page, "utf8");
const gz = zlib.gzipSync(raw, { level: 9 });
const etag = createHash("sha1").update(raw).digest("hex").slice(0, 12);

const hex = [];
for (let i = 0; i < gz.length; i += 24) {
  hex.push("  " + Array.from(gz.subarray(i, i + 24), (b) => "0x" + b.toString(16).padStart(2, "0")).join(","));
}
const header = `// ============================================================================
// web_assets.h: embedded Web UI (PROGMEM, gzip-compressed)
// ============================================================================
// AUTO-GENERATED by tools/build_web.mjs. DO NOT EDIT BY HAND.
// Source: web/webui.html + web/webui.css (Tailwind) + docs/osd-format.js
// Rebuild with:  npm run build:web
//
// Served at http://192.168.4.1 with "Content-Encoding: gzip".
// Uncompressed ${raw.length} bytes, compressed ${gz.length} bytes.
// ============================================================================

#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <stddef.h>
#include <stdint.h>
#include <pgmspace.h>

#define INDEX_HTML_ETAG "\\"${etag}\\""

static const size_t INDEX_HTML_GZ_LEN = ${gz.length};

static const uint8_t INDEX_HTML_GZ[] PROGMEM = {
${hex.join(",\n")}
};

#endif // WEB_ASSETS_H
`;
fs.writeFileSync(r("src", "web_assets.h"), header);
console.log(`src/web_assets.h       ${kb(raw.length)} page -> ${kb(gz.length)} gzipped in flash (css ${kb(css.length)})`);
